language: java

jdk:
        - openjdk8
        

addons:
  sonarcloud:
    organization: "giaquintoraph"
   

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
        - install sonar:sonar
